export const products = [
  {
    code: 'PT001TECH',
    description: 'This mouse is black',
    iva: 12,
    mark: 'SONY',
    name: 'Mouse keyboard',
    percentage_increment: 35,
    public_price: 18.69,
    quantity: 4,
    supplier_price: 12.36
  },
  {
    code: 'PT002TECH',
    description: 'This computer is on stock',
    iva: 12,
    mark: 'DELL',
    name: 'Laptop Dell Inspiron 5567 16 GB RAM',
    percentage_increment: 35,
    public_price: 1667.09,
    quantity: 151,
    supplier_price: 1102.57
  },
  {
    code: 'PT003TECH',
    description: 'Ergonomic wireless mouse',
    iva: 12,
    mark: 'LOGITECH',
    name: 'Wireless Mouse',
    percentage_increment: 35,
    public_price: 38.56,
    quantity: 12,
    supplier_price: 25.5
  },
  {
    code: 'PT004TECH',
    description: 'Docking station for laptops',
    iva: 12,
    mark: 'BELKIN',
    name: 'USB-C Docking Station',
    percentage_increment: 35,
    public_price: 196.54,
    quantity: 6,
    supplier_price: 129.99
  },
  {
    code: 'PT005TECH',
    description: 'Noise-canceling Bluetooth headset',
    iva: 12,
    mark: 'BOSE',
    name: 'Bluetooth Headset',
    percentage_increment: 35,
    public_price: 302.32,
    quantity: 18,
    supplier_price: 199.95
  },
  {
    code: 'PT006TECH',
    description: '27 inch 4K Ultra HD monitor',
    iva: 12,
    mark: 'SAMSUNG',
    name: '4K Monitor',
    percentage_increment: 35,
    public_price: 527.69,
    quantity: 20,
    supplier_price: 349
  },
  {
    code: 'PT007TECH',
    description: 'RGB mechanical keyboard',
    iva: 12,
    mark: 'RAZER',
    name: 'Mechanical Keyboard',
    percentage_increment: 35,
    public_price: 227.93,
    quantity: 47,
    supplier_price: 150.75
  },
  {
    code: 'PT008TECH',
    description: 'Portable solid-state drive',
    iva: 12,
    mark: 'SANDISK',
    name: 'External SSD 1TB',
    percentage_increment: 35,
    public_price: 166.3,
    quantity: 8,
    supplier_price: 109.99
  },
  {
    code: 'PT009TECH',
    description: 'Surround sound gaming headset',
    iva: 12,
    mark: 'LOGITECH',
    name: 'Gaming Headset',
    percentage_increment: 35,
    public_price: 136.06,
    quantity: 18,
    supplier_price: 89.99
  },
  {
    code: 'PT010TECH',
    description: 'Protective sleeve for 15-inch laptops',
    iva: 12,
    mark: 'TARGUS',
    name: 'Laptop Sleeve',
    percentage_increment: 35,
    public_price: 39.3,
    quantity: 10,
    supplier_price: 25.99
  },
  {
    code: 'PT011TECH',
    description: 'Fast-charging power bank',
    iva: 12,
    mark: 'ANKER',
    name: 'Portable Charger 10000mAh',
    percentage_increment: 35,
    public_price: 45.34,
    quantity: 29,
    supplier_price: 29.99
  },
  {
    code: 'PT012TECH',
    description: 'Fast charging USB-C cable',
    iva: 12,
    mark: 'ANKER',
    name: 'Smartphone Charger',
    percentage_increment: 35,
    public_price: 22.68,
    quantity: 5,
    supplier_price: 15
  },
  {
    code: 'PT013TECH',
    description: 'High-speed flash drive',
    iva: 12,
    mark: 'SANDISK',
    name: 'USB Flash Drive 64GB',
    percentage_increment: 35,
    public_price: 30.22,
    quantity: 23,
    supplier_price: 19.99
  },
  {
    code: 'PT014TECH',
    description: 'Water-resistant smart watch',
    iva: 12,
    mark: 'FITBIT',
    name: 'Smart Watch',
    percentage_increment: 35,
    public_price: 196.48,
    quantity: 20,
    supplier_price: 129.95
  },
  {
    code: 'PT015TECH',
    description: 'Adjustable laptop stand',
    iva: 12,
    mark: 'MOFT',
    name: 'Laptop Stand',
    percentage_increment: 35,
    public_price: 45.28,
    quantity: 15,
    supplier_price: 29.95
  },
  {
    code: 'PT016TECH',
    description: 'Qi wireless charging pad',
    iva: 12,
    mark: 'CHOETECH',
    name: 'Wireless Charger',
    percentage_increment: 35,
    public_price: 30.22,
    quantity: 39,
    supplier_price: 19.99
  },
  {
    code: 'PT017TECH',
    description: 'Portable mini projector',
    iva: 12,
    mark: 'ELEPHAS',
    name: 'Mini Projector',
    percentage_increment: 35,
    public_price: 196.54,
    quantity: 12,
    supplier_price: 129.99
  },
  {
    code: 'PT018TECH',
    description: 'Portable wireless speaker',
    iva: 12,
    mark: 'JBL',
    name: 'Bluetooth Speaker',
    percentage_increment: 35,
    public_price: 90.64,
    quantity: 39,
    supplier_price: 59.95
  },
  {
    code: 'PT019TECH',
    description: 'True wireless earbuds with ANC',
    iva: 12,
    mark: 'SONY',
    name: 'Noise-Canceling Earbuds',
    percentage_increment: 35,
    public_price: 302.38,
    quantity: 24,
    supplier_price: 199.99
  },
  {
    code: 'PT020TECH',
    description: 'Adjustable tablet stand',
    iva: 12,
    mark: 'TARGUS',
    name: 'Tablet Stand',
    percentage_increment: 35,
    public_price: 37.78,
    quantity: 24,
    supplier_price: 24.99
  },
  {
    code: 'PT021TECH',
    description: 'Car phone mount holder',
    iva: 12,
    mark: 'MOKO',
    name: 'Smartphone Holder',
    percentage_increment: 35,
    public_price: 19.64,
    quantity: 21,
    supplier_price: 12.99
  },
  {
    code: 'PT022TECH',
    description: 'Virtual Reality headset',
    iva: 12,
    mark: 'OCULUS',
    name: 'VR Headset',
    percentage_increment: 35,
    public_price: 604.78,
    quantity: 3,
    supplier_price: 399.99
  },
  {
    code: 'PT023TECH',
    description: '4K Action camera',
    iva: 12,
    mark: 'GOPro',
    name: 'Action Camera',
    percentage_increment: 35,
    public_price: 377.98,
    quantity: 37,
    supplier_price: 249.99
  },
  {
    code: 'PT024TECH',
    description: 'Smart home controller hub',
    iva: 12,
    mark: 'Amazon',
    name: 'Smart Home Hub',
    percentage_increment: 35,
    public_price: 151.18,
    quantity: 21,
    supplier_price: 99.99
  },
  {
    code: 'PT025TECH',
    description: 'Drone with 4K camera',
    iva: 12,
    mark: 'DJI',
    name: 'Drone with Camera',
    percentage_increment: 35,
    public_price: 907.18,
    quantity: 3,
    supplier_price: 599.99
  },
  {
    code: 'PA002TECH',
    description: 'This wireless mouse is white 2',
    iva: 12,
    mark: 'LOGITECH',
    name: 'Wireless Mouse 2',
    percentage_increment: 25,
    public_price: 140,
    quantity: 6,
    supplier_price: 100
  },
  {
    code: 'PA002TECH',
    description: 'This wireless mouse is white 2',
    iva: 12,
    mark: 'LOGITECH',
    name: 'Wireless Mouse 2',
    percentage_increment: 25,
    public_price: 140,
    quantity: 6,
    supplier_price: 100
  },
  {
    code: 'PA002TECH',
    description: 'This wireless mouse is white 2',
    iva: 12,
    mark: 'LOGITECH',
    name: 'Wireless Mouse 2',
    percentage_increment: 25,
    public_price: 140,
    quantity: 6,
    supplier_price: 100
  },
  {
    code: 'PA002TECH',
    description: 'This wireless mouse is white 2',
    iva: 12,
    mark: 'LOGITECH',
    name: 'Wireless Mouse 2',
    percentage_increment: 25,
    public_price: 140,
    quantity: 6,
    supplier_price: 100
  },
  {
    code: 'PA002TECH',
    description: 'This wireless mouse is white 2',
    iva: 12,
    mark: 'LOGITECH',
    name: 'Wireless Mouse 2',
    percentage_increment: 25,
    public_price: 140,
    quantity: 6,
    supplier_price: 100
  }
];
