/*
For this coding challenge, you'll be working on a set of mini-functions with various mathematical tasks. Let's dive into the following exercises: 

1. Find the total sum of powers of 2 ranging from 2^1 to 2^64. For example: 2**^**1 + 2**^**2 + 2**^**3 + 2**^**4 + … + 2**^**64
2. Calculate the sum of the first 'n' numbers in a sequence where each term, starting from the third, is generated by adding the two preceding terms.
3. Determine the sum of the terms in the series 1^3 + 3^3 + 5^3 + ... + n^3, with 'n' as the given limit.
*/

const powers = (base: number, n: number): number => {
  let total: number = 0;
  for (let exp = 1; exp <= n; exp++) {
    total += base ** exp;
  }
  return total;
};

const fibonacci = (n: number): number => {
  let first: number = 0;
  let second: number = 1;
  let total: number = 0;
  let aux: number = 0;
  for (let index = 0; index < n; index++) {
    aux = first + second;
    total += second;
    first = second;
    second = aux;
  }
  return total;
};

const cubeNum = (n: number): number => {
  let total: number = 0;
  for (let i = 1; i < n; i += 2) {
    total += i ** 3;
  }
  return total;
};

const p: number = powers(2, 64);
console.log(p);
const c: number = fibonacci(10);
console.log(c);
const d: number = cubeNum(10);
console.log(d);
